version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: 123456
  MYSQL_DATABASE: perfanalytics
  REACT_APP_SERVER_PORT: 8080

networks:
  mynet:

volumes:
  mariadb_data:
  phpmyadmin_data:

services:
  mariadb:
    image: mariadb:10.4.8-bionic
    container_name: mariadb_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - mynet
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql/
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mariadb
    links:
      - mariadb:mariadb
    ports:
      - 8000:80
    networks:
      - mynet
    volumes:
      - phpmyadmin_data:/var/www/html/
    restart: always
  server:
    build: ./
    container_name: node_server_container
    depends_on:
      - mariadb
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mariadb
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    networks:
      - mynet
    links:
      - mariadb
    command: yarn server
  client:
    build: ./client
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    networks:
      - mynet
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start